=== PinaeOS/simba/src/main/resources/bean.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="beans">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="aop" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="bean" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="import">
		<xs:complexType>
			<xs:attribute name="url" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="aop">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="target" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="intercepyor" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="bean">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="constructor" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="class" type="xs:string" use="required"/>
			<xs:attribute name="create" type="xs:string"/>
			<xs:attribute name="destroy" type="xs:string"/>
			<xs:attribute name="timeout" type="xs:string"/>
			<xs:attribute name="run" type="xs:string"/>
			<xs:attribute name="singleton">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="false"/>
						<xs:enumeration value="true"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="factory-bean" type="xs:string"/>
			<xs:attribute name="factory-method" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="constructor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="value" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="collection">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="value" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="reflection" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="map">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="entity" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="entity">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="key" type="xs:string"/>
				<xs:element ref="value" minOccurs="0"/>
				<xs:element ref="reflection" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="value" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="reflection" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="set">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="value" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="reflection" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="property">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="reflection"/>
				<xs:element ref="value"/>
				<xs:element ref="map"/>
				<xs:element ref="list"/>
				<xs:element ref="set"/>
				<xs:element ref="collection"/>
			</xs:choice>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="reflection" type="xs:string"/>
	<xs:element name="value">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="null"/>
			</xs:choice>
			<xs:attribute name="class" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="null" type="xs:string"/>
</xs:schema>

=== PinaeOS/simba/src/test/resources/collection.xml
<?xml version="1.0"?>
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bean.xsd">

	<bean name="CollectionBean" class="org.pinae.simba.context.resource.CollectionBean">
		<property name="list">
			<list class="java.util.ArrayList">
				<value>1</value>
				<value>2</value>
				<value>3</value>
				<value>4</value>
				<reflection>Name</reflection>
			</list>
		</property>
		<property name="set">
			<set class="java.util.HashSet">
				<value>1</value>
				<value>2</value>
				<value>3</value>
				<value>4</value>
				<value>5</value>
				<reflection>Name</reflection>
			</set>
		</property>
		<property name="collection">
			<collection class="java.util.ArrayList">
				<value>13343351822</value>
				<value>13240493917</value>
				<value>13702550417</value>
			</collection>
		</property>
	</bean>


</beans>

=== PinaeOS/simba/src/test/resources/map.xml
<?xml version="1.0"?>
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bean.xsd">
	
	<bean name="Map" class="org.pinae.simba.context.resource.MapBean">
		<property name="map">
			<map class="java.util.HashMap">
				<entity>
					<key>huiyugeng</key>
					<value>27</value>
				</entity>
				<entity>
					<key>liuchangqing</key>
					<value>24</value>
				</entity>
				<entity>
					<key>huitiantian</key>
					<reflection>Address</reflection>
				</entity>
			</map>
		</property>
	</bean>
	
</beans>

=== PinaeOS/simba/src/test/java/resource/aop.xml
<?xml version="1.0"?>
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bean.xsd">
	
	<aop name="NameMatcherPointcutAdvisorTest">
		<target>MyTarget</target>

		<intercepyor>NameMatcherPointcutAdvisor</intercepyor>
		<intercepyor>ParameterTypesPointcutAdvisor</intercepyor>
	</aop>

	<bean name="NameMatcherPointcutAdvisor" class="org.pinae.simba.aop.pointcut.NameMatcherPointcutAdvisor">
		<property name="mappedNames">
			<list class="java.util.ArrayList">
				<value>sayHello</value>
				<value>getAge</value>
			</list>
		</property>
		<property name="advice">
			<reflection>AroundAdviceTest</reflection>
		</property>
	</bean>
	
	<bean name="ParameterTypesPointcutAdvisor" class="org.pinae.simba.aop.pointcut.ParameterTypesPointcutAdvisor">
		<property name="class">
			<value>java.lang.String</value>
		</property>
		<property name="advice">
			<reflection>BeforeAdviceTest</reflection>
		</property>
	</bean>
	
	
	<bean name="MyTarget" class="org.pinae.simba.aop.pointcut.resource.MyTarget"/>

	<bean name="AroundAdviceTest" class="org.pinae.simba.aop.pointcut.advice.AroundAdviceTest"/>
	
	<bean name="BeforeAdviceTest" class="org.pinae.simba.aop.pointcut.advice.BeforeAdviceTest"/>

</beans>

=== PinaeOS/simba/src/test/java/resource/person.xml
<?xml version="1.0"?>
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../bean.xsd">
	

	<bean name="PersonFactory" class="org.pinae.simba.context.resource.Person"
		factory-bean="org.pinae.simba.context.resource.PersonFactory" 
		factory-method="getPerson"
		create="create" run="run" singleton="true" 
		timeout="3" destroy="destroy">
		
		<property name="name">
			<reflection>Name</reflection>
		</property>
		<property name="age">
			<value>27</value>
		</property>
		<property name="address">
			<reflection>Address</reflection>
		</property>
		<property name="email">
			<value>interhui@21cn.com</value>
		</property>
		<property name="admin">
			<value>true</value>
		</property>
	</bean>
	
	<bean name="Name" class="org.pinae.simba.context.resource.Name">
		<constructor>
			<value>hui</value>
			<value>yugeng</value>
		</constructor>
	</bean>
	
	<bean name="Address" class="org.pinae.simba.context.resource.Address">
		<property name="country">
			<value>China</value>
		</property>
		<property name="province">
			<value>Guangdong</value>
		</property>
		<property name="city">
			<value><null/></value>
		</property>
	</bean>
</beans>

=== PinaeOS/simba/src/test/resources/example.xml
<?xml version="1.0"?>
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="resource/bean.xsd">
	<import url=""/>
	<import url=""/>
	
	<aop name="">
		<target></target>
		<intercept></intercept>
	</aop>
	
	<bean name="" class="" create="" run="" singleton="true">
		<constructor>
			<value class=""/>
			<value/>
		</constructor>
	</bean>
	<bean name="" class="" singleton="false" factory-bean="" factory-method="">
		<property name="">
			<reflection/>
		</property>
	</bean>
	<bean name="" class="">
		<property name="">
			<value/>
		</property>
		<property name="">
			<value>
				<null/>
			</value>
		</property>
	</bean>
	<bean name="" class="">
		<property name="">
			<map class="">
				<entity>
					<key> </key>
					<value> </value>
				</entity>
				<entity>
					<key/>
					<value/>
				</entity>
				<entity>
					<key/>
					<reflection/>
				</entity>
			</map>
		</property>
	</bean>
	<bean name="" class="">
		<property name="">
			<list class="">
				<value/>
				<value/>
				<reflection/>
			</list>
		</property>
	</bean>
	<bean name="" class="">
		<property name="">
			<set class="">
				<value/>
				<value/>
				<reflection/>
			</set>
		</property>
	</bean>
	<bean name="" class="">
		<property name="">
			<collection class="">
				<value>empty</value>
				<value/>
				<value/>
				<reflection/>
			</collection>
		</property>
	</bean>
</beans>
